#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseConnector
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="C:\\Users\\Игорь\\OneDrive\\Develop\\FTE\\FTE_counter\\DataBaseConnector\\Statistic.sdf")]
	public partial class StatisticContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void InsertEmployees(Employees instance);
    partial void UpdateEmployees(Employees instance);
    partial void DeleteEmployees(Employees instance);
    partial void InsertFTE(FTE instance);
    partial void UpdateFTE(FTE instance);
    partial void DeleteFTE(FTE instance);
    partial void InsertSd_employee(Sd_employee instance);
    partial void UpdateSd_employee(Sd_employee instance);
    partial void DeleteSd_employee(Sd_employee instance);
    partial void InsertSd_zno(Sd_zno instance);
    partial void UpdateSd_zno(Sd_zno instance);
    partial void DeleteSd_zno(Sd_zno instance);
    partial void InsertSd_znr(Sd_znr instance);
    partial void UpdateSd_znr(Sd_znr instance);
    partial void DeleteSd_znr(Sd_znr instance);
    partial void InsertSm_employee(Sm_employee instance);
    partial void UpdateSm_employee(Sm_employee instance);
    partial void DeleteSm_employee(Sm_employee instance);
    partial void InsertSm_inc(Sm_inc instance);
    partial void UpdateSm_inc(Sm_inc instance);
    partial void DeleteSm_inc(Sm_inc instance);
    partial void InsertSm_zno(Sm_zno instance);
    partial void UpdateSm_zno(Sm_zno instance);
    partial void DeleteSm_zno(Sm_zno instance);
    #endregion
		
		public StatisticContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StatisticContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StatisticContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StatisticContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Employees> Employees
		{
			get
			{
				return this.GetTable<Employees>();
			}
		}
		
		public System.Data.Linq.Table<FTE> FTE
		{
			get
			{
				return this.GetTable<FTE>();
			}
		}
		
		public System.Data.Linq.Table<Sd_employee> Sd_employee
		{
			get
			{
				return this.GetTable<Sd_employee>();
			}
		}
		
		public System.Data.Linq.Table<Sd_zno> Sd_zno
		{
			get
			{
				return this.GetTable<Sd_zno>();
			}
		}
		
		public System.Data.Linq.Table<Sd_znr> Sd_znr
		{
			get
			{
				return this.GetTable<Sd_znr>();
			}
		}
		
		public System.Data.Linq.Table<Sm_employee> Sm_employee
		{
			get
			{
				return this.GetTable<Sm_employee>();
			}
		}
		
		public System.Data.Linq.Table<Sm_inc> Sm_inc
		{
			get
			{
				return this.GetTable<Sm_inc>();
			}
		}
		
		public System.Data.Linq.Table<Sm_zno> Sm_zno
		{
			get
			{
				return this.GetTable<Sm_zno>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="employees")]
	public partial class Employees : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Full_Name;
		
		private string _First_Name;
		
		private string _Last_Name;
		
		private string _Middle_Name;
		
		private string _SD_alias;
		
		private string _SD_alias0;
		
		private string _SD_alias1;
		
		private string _SM_alias;
		
		private string _SM_alias0;
		
		private string _SM_alias1;
		
		private string _SERCH_PATTERN;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnFull_NameChanging(string value);
    partial void OnFull_NameChanged();
    partial void OnFirst_NameChanging(string value);
    partial void OnFirst_NameChanged();
    partial void OnLast_NameChanging(string value);
    partial void OnLast_NameChanged();
    partial void OnMiddle_NameChanging(string value);
    partial void OnMiddle_NameChanged();
    partial void OnSD_aliasChanging(string value);
    partial void OnSD_aliasChanged();
    partial void OnSD_alias0Changing(string value);
    partial void OnSD_alias0Changed();
    partial void OnSD_alias1Changing(string value);
    partial void OnSD_alias1Changed();
    partial void OnSM_aliasChanging(string value);
    partial void OnSM_aliasChanged();
    partial void OnSM_alias0Changing(string value);
    partial void OnSM_alias0Changed();
    partial void OnSM_alias1Changing(string value);
    partial void OnSM_alias1Changed();
    partial void OnSERCH_PATTERNChanging(string value);
    partial void OnSERCH_PATTERNChanged();
    #endregion
		
		public Employees()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Full_Name", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Full_Name
		{
			get
			{
				return this._Full_Name;
			}
			set
			{
				if ((this._Full_Name != value))
				{
					this.OnFull_NameChanging(value);
					this.SendPropertyChanging();
					this._Full_Name = value;
					this.SendPropertyChanged("Full_Name");
					this.OnFull_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_First_Name", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string First_Name
		{
			get
			{
				return this._First_Name;
			}
			set
			{
				if ((this._First_Name != value))
				{
					this.OnFirst_NameChanging(value);
					this.SendPropertyChanging();
					this._First_Name = value;
					this.SendPropertyChanged("First_Name");
					this.OnFirst_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_Name", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Last_Name
		{
			get
			{
				return this._Last_Name;
			}
			set
			{
				if ((this._Last_Name != value))
				{
					this.OnLast_NameChanging(value);
					this.SendPropertyChanging();
					this._Last_Name = value;
					this.SendPropertyChanged("Last_Name");
					this.OnLast_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Middle_Name", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Middle_Name
		{
			get
			{
				return this._Middle_Name;
			}
			set
			{
				if ((this._Middle_Name != value))
				{
					this.OnMiddle_NameChanging(value);
					this.SendPropertyChanging();
					this._Middle_Name = value;
					this.SendPropertyChanged("Middle_Name");
					this.OnMiddle_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SD_alias", DbType="NVarChar(250)")]
		public string SD_alias
		{
			get
			{
				return this._SD_alias;
			}
			set
			{
				if ((this._SD_alias != value))
				{
					this.OnSD_aliasChanging(value);
					this.SendPropertyChanging();
					this._SD_alias = value;
					this.SendPropertyChanged("SD_alias");
					this.OnSD_aliasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SD_alias0", DbType="NVarChar(250)")]
		public string SD_alias0
		{
			get
			{
				return this._SD_alias0;
			}
			set
			{
				if ((this._SD_alias0 != value))
				{
					this.OnSD_alias0Changing(value);
					this.SendPropertyChanging();
					this._SD_alias0 = value;
					this.SendPropertyChanged("SD_alias0");
					this.OnSD_alias0Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SD_alias1", DbType="NVarChar(250)")]
		public string SD_alias1
		{
			get
			{
				return this._SD_alias1;
			}
			set
			{
				if ((this._SD_alias1 != value))
				{
					this.OnSD_alias1Changing(value);
					this.SendPropertyChanging();
					this._SD_alias1 = value;
					this.SendPropertyChanged("SD_alias1");
					this.OnSD_alias1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SM_alias", DbType="NVarChar(250)")]
		public string SM_alias
		{
			get
			{
				return this._SM_alias;
			}
			set
			{
				if ((this._SM_alias != value))
				{
					this.OnSM_aliasChanging(value);
					this.SendPropertyChanging();
					this._SM_alias = value;
					this.SendPropertyChanged("SM_alias");
					this.OnSM_aliasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SM_alias0", DbType="NVarChar(250)")]
		public string SM_alias0
		{
			get
			{
				return this._SM_alias0;
			}
			set
			{
				if ((this._SM_alias0 != value))
				{
					this.OnSM_alias0Changing(value);
					this.SendPropertyChanging();
					this._SM_alias0 = value;
					this.SendPropertyChanged("SM_alias0");
					this.OnSM_alias0Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SM_alias1", DbType="NVarChar(250)")]
		public string SM_alias1
		{
			get
			{
				return this._SM_alias1;
			}
			set
			{
				if ((this._SM_alias1 != value))
				{
					this.OnSM_alias1Changing(value);
					this.SendPropertyChanging();
					this._SM_alias1 = value;
					this.SendPropertyChanged("SM_alias1");
					this.OnSM_alias1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERCH_PATTERN", DbType="NVarChar(250)")]
		public string SERCH_PATTERN
		{
			get
			{
				return this._SERCH_PATTERN;
			}
			set
			{
				if ((this._SERCH_PATTERN != value))
				{
					this.OnSERCH_PATTERNChanging(value);
					this.SendPropertyChanging();
					this._SERCH_PATTERN = value;
					this.SendPropertyChanged("SERCH_PATTERN");
					this.OnSERCH_PATTERNChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class FTE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _Employee_id;
		
		private System.Nullable<int> _Sm_inc_1line;
		
		private System.Nullable<int> _Sm_inc_dost;
		
		private System.Nullable<int> _Sm_inc_disp;
		
		private System.Nullable<int> _Sm_zno_1line;
		
		private System.Nullable<int> _Sm_zno_dost;
		
		private System.Nullable<int> _Sm_zno_disp;
		
		private System.Nullable<int> _Sd_zno_1line;
		
		private System.Nullable<int> _Sd_zno_dost;
		
		private System.Nullable<int> _Sd_zno_disp;
		
		private System.Nullable<int> _Sd_znr_1line;
		
		private System.Nullable<int> _Sd_znr_dost;
		
		private System.Nullable<int> _Sd_znr_disp;
		
		private System.Nullable<int> _Sm_inc_fte;
		
		private System.Nullable<int> _Sm_zno_fte;
		
		private System.Nullable<int> _Sd_zno_fte;
		
		private System.Nullable<int> _Sd_znr_fte;
		
		private string _Employee_short_name;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnEmployee_idChanging(int value);
    partial void OnEmployee_idChanged();
    partial void OnSm_inc_1lineChanging(System.Nullable<int> value);
    partial void OnSm_inc_1lineChanged();
    partial void OnSm_inc_dostChanging(System.Nullable<int> value);
    partial void OnSm_inc_dostChanged();
    partial void OnSm_inc_dispChanging(System.Nullable<int> value);
    partial void OnSm_inc_dispChanged();
    partial void OnSm_zno_1lineChanging(System.Nullable<int> value);
    partial void OnSm_zno_1lineChanged();
    partial void OnSm_zno_dostChanging(System.Nullable<int> value);
    partial void OnSm_zno_dostChanged();
    partial void OnSm_zno_dispChanging(System.Nullable<int> value);
    partial void OnSm_zno_dispChanged();
    partial void OnSd_zno_1lineChanging(System.Nullable<int> value);
    partial void OnSd_zno_1lineChanged();
    partial void OnSd_zno_dostChanging(System.Nullable<int> value);
    partial void OnSd_zno_dostChanged();
    partial void OnSd_zno_dispChanging(System.Nullable<int> value);
    partial void OnSd_zno_dispChanged();
    partial void OnSd_znr_1lineChanging(System.Nullable<int> value);
    partial void OnSd_znr_1lineChanged();
    partial void OnSd_znr_dostChanging(System.Nullable<int> value);
    partial void OnSd_znr_dostChanged();
    partial void OnSd_znr_dispChanging(System.Nullable<int> value);
    partial void OnSd_znr_dispChanged();
    partial void OnSm_inc_fteChanging(System.Nullable<int> value);
    partial void OnSm_inc_fteChanged();
    partial void OnSm_zno_fteChanging(System.Nullable<int> value);
    partial void OnSm_zno_fteChanged();
    partial void OnSd_zno_fteChanging(System.Nullable<int> value);
    partial void OnSd_zno_fteChanged();
    partial void OnSd_znr_fteChanging(System.Nullable<int> value);
    partial void OnSd_znr_fteChanged();
    partial void OnEmployee_short_nameChanging(string value);
    partial void OnEmployee_short_nameChanged();
    #endregion
		
		public FTE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="employee_id", Storage="_Employee_id", DbType="Int NOT NULL")]
		public int Employee_id
		{
			get
			{
				return this._Employee_id;
			}
			set
			{
				if ((this._Employee_id != value))
				{
					this.OnEmployee_idChanging(value);
					this.SendPropertyChanging();
					this._Employee_id = value;
					this.SendPropertyChanged("Employee_id");
					this.OnEmployee_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="sm_inc_1line", Storage="_Sm_inc_1line", DbType="Int")]
		public System.Nullable<int> Sm_inc_1line
		{
			get
			{
				return this._Sm_inc_1line;
			}
			set
			{
				if ((this._Sm_inc_1line != value))
				{
					this.OnSm_inc_1lineChanging(value);
					this.SendPropertyChanging();
					this._Sm_inc_1line = value;
					this.SendPropertyChanged("Sm_inc_1line");
					this.OnSm_inc_1lineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="sm_inc_dost", Storage="_Sm_inc_dost", DbType="Int")]
		public System.Nullable<int> Sm_inc_dost
		{
			get
			{
				return this._Sm_inc_dost;
			}
			set
			{
				if ((this._Sm_inc_dost != value))
				{
					this.OnSm_inc_dostChanging(value);
					this.SendPropertyChanging();
					this._Sm_inc_dost = value;
					this.SendPropertyChanged("Sm_inc_dost");
					this.OnSm_inc_dostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="sm_inc_disp", Storage="_Sm_inc_disp", DbType="Int")]
		public System.Nullable<int> Sm_inc_disp
		{
			get
			{
				return this._Sm_inc_disp;
			}
			set
			{
				if ((this._Sm_inc_disp != value))
				{
					this.OnSm_inc_dispChanging(value);
					this.SendPropertyChanging();
					this._Sm_inc_disp = value;
					this.SendPropertyChanged("Sm_inc_disp");
					this.OnSm_inc_dispChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="sm_zno_1line", Storage="_Sm_zno_1line", DbType="Int")]
		public System.Nullable<int> Sm_zno_1line
		{
			get
			{
				return this._Sm_zno_1line;
			}
			set
			{
				if ((this._Sm_zno_1line != value))
				{
					this.OnSm_zno_1lineChanging(value);
					this.SendPropertyChanging();
					this._Sm_zno_1line = value;
					this.SendPropertyChanged("Sm_zno_1line");
					this.OnSm_zno_1lineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="sm_zno_dost", Storage="_Sm_zno_dost", DbType="Int")]
		public System.Nullable<int> Sm_zno_dost
		{
			get
			{
				return this._Sm_zno_dost;
			}
			set
			{
				if ((this._Sm_zno_dost != value))
				{
					this.OnSm_zno_dostChanging(value);
					this.SendPropertyChanging();
					this._Sm_zno_dost = value;
					this.SendPropertyChanged("Sm_zno_dost");
					this.OnSm_zno_dostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="sm_zno_disp", Storage="_Sm_zno_disp", DbType="Int")]
		public System.Nullable<int> Sm_zno_disp
		{
			get
			{
				return this._Sm_zno_disp;
			}
			set
			{
				if ((this._Sm_zno_disp != value))
				{
					this.OnSm_zno_dispChanging(value);
					this.SendPropertyChanging();
					this._Sm_zno_disp = value;
					this.SendPropertyChanged("Sm_zno_disp");
					this.OnSm_zno_dispChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="sd_zno_1line", Storage="_Sd_zno_1line", DbType="Int")]
		public System.Nullable<int> Sd_zno_1line
		{
			get
			{
				return this._Sd_zno_1line;
			}
			set
			{
				if ((this._Sd_zno_1line != value))
				{
					this.OnSd_zno_1lineChanging(value);
					this.SendPropertyChanging();
					this._Sd_zno_1line = value;
					this.SendPropertyChanged("Sd_zno_1line");
					this.OnSd_zno_1lineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="sd_zno_dost", Storage="_Sd_zno_dost", DbType="Int")]
		public System.Nullable<int> Sd_zno_dost
		{
			get
			{
				return this._Sd_zno_dost;
			}
			set
			{
				if ((this._Sd_zno_dost != value))
				{
					this.OnSd_zno_dostChanging(value);
					this.SendPropertyChanging();
					this._Sd_zno_dost = value;
					this.SendPropertyChanged("Sd_zno_dost");
					this.OnSd_zno_dostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="sd_zno_disp", Storage="_Sd_zno_disp", DbType="Int")]
		public System.Nullable<int> Sd_zno_disp
		{
			get
			{
				return this._Sd_zno_disp;
			}
			set
			{
				if ((this._Sd_zno_disp != value))
				{
					this.OnSd_zno_dispChanging(value);
					this.SendPropertyChanging();
					this._Sd_zno_disp = value;
					this.SendPropertyChanged("Sd_zno_disp");
					this.OnSd_zno_dispChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="sd_znr_1line", Storage="_Sd_znr_1line", DbType="Int")]
		public System.Nullable<int> Sd_znr_1line
		{
			get
			{
				return this._Sd_znr_1line;
			}
			set
			{
				if ((this._Sd_znr_1line != value))
				{
					this.OnSd_znr_1lineChanging(value);
					this.SendPropertyChanging();
					this._Sd_znr_1line = value;
					this.SendPropertyChanged("Sd_znr_1line");
					this.OnSd_znr_1lineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="sd_znr_dost", Storage="_Sd_znr_dost", DbType="Int")]
		public System.Nullable<int> Sd_znr_dost
		{
			get
			{
				return this._Sd_znr_dost;
			}
			set
			{
				if ((this._Sd_znr_dost != value))
				{
					this.OnSd_znr_dostChanging(value);
					this.SendPropertyChanging();
					this._Sd_znr_dost = value;
					this.SendPropertyChanged("Sd_znr_dost");
					this.OnSd_znr_dostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="sd_znr_disp", Storage="_Sd_znr_disp", DbType="Int")]
		public System.Nullable<int> Sd_znr_disp
		{
			get
			{
				return this._Sd_znr_disp;
			}
			set
			{
				if ((this._Sd_znr_disp != value))
				{
					this.OnSd_znr_dispChanging(value);
					this.SendPropertyChanging();
					this._Sd_znr_disp = value;
					this.SendPropertyChanged("Sd_znr_disp");
					this.OnSd_znr_dispChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="sm_inc_fte", Storage="_Sm_inc_fte", DbType="Int")]
		public System.Nullable<int> Sm_inc_fte
		{
			get
			{
				return this._Sm_inc_fte;
			}
			set
			{
				if ((this._Sm_inc_fte != value))
				{
					this.OnSm_inc_fteChanging(value);
					this.SendPropertyChanging();
					this._Sm_inc_fte = value;
					this.SendPropertyChanged("Sm_inc_fte");
					this.OnSm_inc_fteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="sm_zno_fte", Storage="_Sm_zno_fte", DbType="Int")]
		public System.Nullable<int> Sm_zno_fte
		{
			get
			{
				return this._Sm_zno_fte;
			}
			set
			{
				if ((this._Sm_zno_fte != value))
				{
					this.OnSm_zno_fteChanging(value);
					this.SendPropertyChanging();
					this._Sm_zno_fte = value;
					this.SendPropertyChanged("Sm_zno_fte");
					this.OnSm_zno_fteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="sd_zno_fte", Storage="_Sd_zno_fte", DbType="Int")]
		public System.Nullable<int> Sd_zno_fte
		{
			get
			{
				return this._Sd_zno_fte;
			}
			set
			{
				if ((this._Sd_zno_fte != value))
				{
					this.OnSd_zno_fteChanging(value);
					this.SendPropertyChanging();
					this._Sd_zno_fte = value;
					this.SendPropertyChanged("Sd_zno_fte");
					this.OnSd_zno_fteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="sd_znr_fte", Storage="_Sd_znr_fte", DbType="Int")]
		public System.Nullable<int> Sd_znr_fte
		{
			get
			{
				return this._Sd_znr_fte;
			}
			set
			{
				if ((this._Sd_znr_fte != value))
				{
					this.OnSd_znr_fteChanging(value);
					this.SendPropertyChanging();
					this._Sd_znr_fte = value;
					this.SendPropertyChanged("Sd_znr_fte");
					this.OnSd_znr_fteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="employee_short_name", Storage="_Employee_short_name", DbType="NVarChar(250)")]
		public string Employee_short_name
		{
			get
			{
				return this._Employee_short_name;
			}
			set
			{
				if ((this._Employee_short_name != value))
				{
					this.OnEmployee_short_nameChanging(value);
					this.SendPropertyChanging();
					this._Employee_short_name = value;
					this.SendPropertyChanged("Employee_short_name");
					this.OnEmployee_short_nameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="sd_employee")]
	public partial class Sd_employee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Employee;
		
		private string _Full_Name;
		
		private System.Nullable<int> _Id_employee;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnEmployeeChanging(string value);
    partial void OnEmployeeChanged();
    partial void OnFull_NameChanging(string value);
    partial void OnFull_NameChanged();
    partial void OnId_employeeChanging(System.Nullable<int> value);
    partial void OnId_employeeChanged();
    #endregion
		
		public Sd_employee()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="employee", Storage="_Employee", DbType="NVarChar(250)")]
		public string Employee
		{
			get
			{
				return this._Employee;
			}
			set
			{
				if ((this._Employee != value))
				{
					this.OnEmployeeChanging(value);
					this.SendPropertyChanging();
					this._Employee = value;
					this.SendPropertyChanged("Employee");
					this.OnEmployeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="full_Name", Storage="_Full_Name", DbType="NVarChar(250)")]
		public string Full_Name
		{
			get
			{
				return this._Full_Name;
			}
			set
			{
				if ((this._Full_Name != value))
				{
					this.OnFull_NameChanging(value);
					this.SendPropertyChanging();
					this._Full_Name = value;
					this.SendPropertyChanged("Full_Name");
					this.OnFull_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_employee", Storage="_Id_employee", DbType="Int")]
		public System.Nullable<int> Id_employee
		{
			get
			{
				return this._Id_employee;
			}
			set
			{
				if ((this._Id_employee != value))
				{
					this.OnId_employeeChanging(value);
					this.SendPropertyChanging();
					this._Id_employee = value;
					this.SendPropertyChanged("Id_employee");
					this.OnId_employeeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="sd_zno")]
	public partial class Sd_zno : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _Id_sd_zno;
		
		private string _Template;
		
		private System.DateTime _Cr_date;
		
		private System.DateTime _C_date;
		
		private string _Category;
		
		private string _Ca_task_id;
		
		private string _Ca_task_name;
		
		private string _Ca_task_category;
		
		private string _Employee;
		
		private string _Work_group;
		
		private System.Nullable<int> _Id_employee;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnId_sd_znoChanging(int value);
    partial void OnId_sd_znoChanged();
    partial void OnTemplateChanging(string value);
    partial void OnTemplateChanged();
    partial void OnCr_dateChanging(System.DateTime value);
    partial void OnCr_dateChanged();
    partial void OnC_dateChanging(System.DateTime value);
    partial void OnC_dateChanged();
    partial void OnCategoryChanging(string value);
    partial void OnCategoryChanged();
    partial void OnCa_task_idChanging(string value);
    partial void OnCa_task_idChanged();
    partial void OnCa_task_nameChanging(string value);
    partial void OnCa_task_nameChanged();
    partial void OnCa_task_categoryChanging(string value);
    partial void OnCa_task_categoryChanged();
    partial void OnEmployeeChanging(string value);
    partial void OnEmployeeChanged();
    partial void OnWork_groupChanging(string value);
    partial void OnWork_groupChanged();
    partial void OnId_employeeChanging(System.Nullable<int> value);
    partial void OnId_employeeChanged();
    #endregion
		
		public Sd_zno()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_sd_zno", Storage="_Id_sd_zno", DbType="Int NOT NULL")]
		public int Id_sd_zno
		{
			get
			{
				return this._Id_sd_zno;
			}
			set
			{
				if ((this._Id_sd_zno != value))
				{
					this.OnId_sd_znoChanging(value);
					this.SendPropertyChanging();
					this._Id_sd_zno = value;
					this.SendPropertyChanged("Id_sd_zno");
					this.OnId_sd_znoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="template", Storage="_Template", DbType="NVarChar(250)")]
		public string Template
		{
			get
			{
				return this._Template;
			}
			set
			{
				if ((this._Template != value))
				{
					this.OnTemplateChanging(value);
					this.SendPropertyChanging();
					this._Template = value;
					this.SendPropertyChanged("Template");
					this.OnTemplateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="cr_date", Storage="_Cr_date", DbType="DateTime NOT NULL")]
		public System.DateTime Cr_date
		{
			get
			{
				return this._Cr_date;
			}
			set
			{
				if ((this._Cr_date != value))
				{
					this.OnCr_dateChanging(value);
					this.SendPropertyChanging();
					this._Cr_date = value;
					this.SendPropertyChanged("Cr_date");
					this.OnCr_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="c_date", Storage="_C_date", DbType="DateTime NOT NULL")]
		public System.DateTime C_date
		{
			get
			{
				return this._C_date;
			}
			set
			{
				if ((this._C_date != value))
				{
					this.OnC_dateChanging(value);
					this.SendPropertyChanging();
					this._C_date = value;
					this.SendPropertyChanged("C_date");
					this.OnC_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="category", Storage="_Category", DbType="NVarChar(250)")]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this.OnCategoryChanging(value);
					this.SendPropertyChanging();
					this._Category = value;
					this.SendPropertyChanged("Category");
					this.OnCategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ca_task_id", Storage="_Ca_task_id", DbType="NVarChar(250)")]
		public string Ca_task_id
		{
			get
			{
				return this._Ca_task_id;
			}
			set
			{
				if ((this._Ca_task_id != value))
				{
					this.OnCa_task_idChanging(value);
					this.SendPropertyChanging();
					this._Ca_task_id = value;
					this.SendPropertyChanged("Ca_task_id");
					this.OnCa_task_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ca_task_name", Storage="_Ca_task_name", DbType="NVarChar(250)")]
		public string Ca_task_name
		{
			get
			{
				return this._Ca_task_name;
			}
			set
			{
				if ((this._Ca_task_name != value))
				{
					this.OnCa_task_nameChanging(value);
					this.SendPropertyChanging();
					this._Ca_task_name = value;
					this.SendPropertyChanged("Ca_task_name");
					this.OnCa_task_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ca_task_category", Storage="_Ca_task_category", DbType="NVarChar(250)")]
		public string Ca_task_category
		{
			get
			{
				return this._Ca_task_category;
			}
			set
			{
				if ((this._Ca_task_category != value))
				{
					this.OnCa_task_categoryChanging(value);
					this.SendPropertyChanging();
					this._Ca_task_category = value;
					this.SendPropertyChanged("Ca_task_category");
					this.OnCa_task_categoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="employee", Storage="_Employee", DbType="NVarChar(250)")]
		public string Employee
		{
			get
			{
				return this._Employee;
			}
			set
			{
				if ((this._Employee != value))
				{
					this.OnEmployeeChanging(value);
					this.SendPropertyChanging();
					this._Employee = value;
					this.SendPropertyChanged("Employee");
					this.OnEmployeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="work_group", Storage="_Work_group", DbType="NVarChar(250)")]
		public string Work_group
		{
			get
			{
				return this._Work_group;
			}
			set
			{
				if ((this._Work_group != value))
				{
					this.OnWork_groupChanging(value);
					this.SendPropertyChanging();
					this._Work_group = value;
					this.SendPropertyChanged("Work_group");
					this.OnWork_groupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_employee", Storage="_Id_employee", DbType="Int")]
		public System.Nullable<int> Id_employee
		{
			get
			{
				return this._Id_employee;
			}
			set
			{
				if ((this._Id_employee != value))
				{
					this.OnId_employeeChanging(value);
					this.SendPropertyChanging();
					this._Id_employee = value;
					this.SendPropertyChanged("Id_employee");
					this.OnId_employeeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="sd_znr")]
	public partial class Sd_znr : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _Id_sd_znr;
		
		private string _Template;
		
		private System.DateTime _Cr_date;
		
		private System.DateTime _C_date;
		
		private string _Category;
		
		private string _Ca_task_id;
		
		private string _Ca_task_name;
		
		private string _Ca_task_category;
		
		private string _Work_group;
		
		private string _Employee;
		
		private int _N_users;
		
		private System.Nullable<int> _Id_employee;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnId_sd_znrChanging(int value);
    partial void OnId_sd_znrChanged();
    partial void OnTemplateChanging(string value);
    partial void OnTemplateChanged();
    partial void OnCr_dateChanging(System.DateTime value);
    partial void OnCr_dateChanged();
    partial void OnC_dateChanging(System.DateTime value);
    partial void OnC_dateChanged();
    partial void OnCategoryChanging(string value);
    partial void OnCategoryChanged();
    partial void OnCa_task_idChanging(string value);
    partial void OnCa_task_idChanged();
    partial void OnCa_task_nameChanging(string value);
    partial void OnCa_task_nameChanged();
    partial void OnCa_task_categoryChanging(string value);
    partial void OnCa_task_categoryChanged();
    partial void OnWork_groupChanging(string value);
    partial void OnWork_groupChanged();
    partial void OnEmployeeChanging(string value);
    partial void OnEmployeeChanged();
    partial void OnN_usersChanging(int value);
    partial void OnN_usersChanged();
    partial void OnId_employeeChanging(System.Nullable<int> value);
    partial void OnId_employeeChanged();
    #endregion
		
		public Sd_znr()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_sd_znr", Storage="_Id_sd_znr", DbType="Int NOT NULL")]
		public int Id_sd_znr
		{
			get
			{
				return this._Id_sd_znr;
			}
			set
			{
				if ((this._Id_sd_znr != value))
				{
					this.OnId_sd_znrChanging(value);
					this.SendPropertyChanging();
					this._Id_sd_znr = value;
					this.SendPropertyChanged("Id_sd_znr");
					this.OnId_sd_znrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="template", Storage="_Template", DbType="NVarChar(250)")]
		public string Template
		{
			get
			{
				return this._Template;
			}
			set
			{
				if ((this._Template != value))
				{
					this.OnTemplateChanging(value);
					this.SendPropertyChanging();
					this._Template = value;
					this.SendPropertyChanged("Template");
					this.OnTemplateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="cr_date", Storage="_Cr_date", DbType="DateTime NOT NULL")]
		public System.DateTime Cr_date
		{
			get
			{
				return this._Cr_date;
			}
			set
			{
				if ((this._Cr_date != value))
				{
					this.OnCr_dateChanging(value);
					this.SendPropertyChanging();
					this._Cr_date = value;
					this.SendPropertyChanged("Cr_date");
					this.OnCr_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="c_date", Storage="_C_date", DbType="DateTime NOT NULL")]
		public System.DateTime C_date
		{
			get
			{
				return this._C_date;
			}
			set
			{
				if ((this._C_date != value))
				{
					this.OnC_dateChanging(value);
					this.SendPropertyChanging();
					this._C_date = value;
					this.SendPropertyChanged("C_date");
					this.OnC_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="category", Storage="_Category", DbType="NVarChar(250)")]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this.OnCategoryChanging(value);
					this.SendPropertyChanging();
					this._Category = value;
					this.SendPropertyChanged("Category");
					this.OnCategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ca_task_id", Storage="_Ca_task_id", DbType="NVarChar(250)")]
		public string Ca_task_id
		{
			get
			{
				return this._Ca_task_id;
			}
			set
			{
				if ((this._Ca_task_id != value))
				{
					this.OnCa_task_idChanging(value);
					this.SendPropertyChanging();
					this._Ca_task_id = value;
					this.SendPropertyChanged("Ca_task_id");
					this.OnCa_task_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ca_task_name", Storage="_Ca_task_name", DbType="NVarChar(250)")]
		public string Ca_task_name
		{
			get
			{
				return this._Ca_task_name;
			}
			set
			{
				if ((this._Ca_task_name != value))
				{
					this.OnCa_task_nameChanging(value);
					this.SendPropertyChanging();
					this._Ca_task_name = value;
					this.SendPropertyChanged("Ca_task_name");
					this.OnCa_task_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ca_task_category", Storage="_Ca_task_category", DbType="NVarChar(250)")]
		public string Ca_task_category
		{
			get
			{
				return this._Ca_task_category;
			}
			set
			{
				if ((this._Ca_task_category != value))
				{
					this.OnCa_task_categoryChanging(value);
					this.SendPropertyChanging();
					this._Ca_task_category = value;
					this.SendPropertyChanged("Ca_task_category");
					this.OnCa_task_categoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="work_group", Storage="_Work_group", DbType="NVarChar(250)")]
		public string Work_group
		{
			get
			{
				return this._Work_group;
			}
			set
			{
				if ((this._Work_group != value))
				{
					this.OnWork_groupChanging(value);
					this.SendPropertyChanging();
					this._Work_group = value;
					this.SendPropertyChanged("Work_group");
					this.OnWork_groupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="employee", Storage="_Employee", DbType="NVarChar(250)")]
		public string Employee
		{
			get
			{
				return this._Employee;
			}
			set
			{
				if ((this._Employee != value))
				{
					this.OnEmployeeChanging(value);
					this.SendPropertyChanging();
					this._Employee = value;
					this.SendPropertyChanged("Employee");
					this.OnEmployeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="n_users", Storage="_N_users", DbType="Int NOT NULL")]
		public int N_users
		{
			get
			{
				return this._N_users;
			}
			set
			{
				if ((this._N_users != value))
				{
					this.OnN_usersChanging(value);
					this.SendPropertyChanging();
					this._N_users = value;
					this.SendPropertyChanged("N_users");
					this.OnN_usersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_employee", Storage="_Id_employee", DbType="Int")]
		public System.Nullable<int> Id_employee
		{
			get
			{
				return this._Id_employee;
			}
			set
			{
				if ((this._Id_employee != value))
				{
					this.OnId_employeeChanging(value);
					this.SendPropertyChanging();
					this._Id_employee = value;
					this.SendPropertyChanged("Id_employee");
					this.OnId_employeeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="sm_employee")]
	public partial class Sm_employee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Employee;
		
		private System.Nullable<int> _Id_employee;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnEmployeeChanging(string value);
    partial void OnEmployeeChanged();
    partial void OnId_employeeChanging(System.Nullable<int> value);
    partial void OnId_employeeChanged();
    #endregion
		
		public Sm_employee()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="employee", Storage="_Employee", DbType="NVarChar(250)")]
		public string Employee
		{
			get
			{
				return this._Employee;
			}
			set
			{
				if ((this._Employee != value))
				{
					this.OnEmployeeChanging(value);
					this.SendPropertyChanging();
					this._Employee = value;
					this.SendPropertyChanged("Employee");
					this.OnEmployeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_employee", Storage="_Id_employee", DbType="Int")]
		public System.Nullable<int> Id_employee
		{
			get
			{
				return this._Id_employee;
			}
			set
			{
				if ((this._Id_employee != value))
				{
					this.OnId_employeeChanging(value);
					this.SendPropertyChanging();
					this._Id_employee = value;
					this.SendPropertyChanged("Id_employee");
					this.OnId_employeeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="sm_inc")]
	public partial class Sm_inc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _To_the_target_date;
		
		private string _Id_sm_inc;
		
		private string _Number_of_object;
		
		private string _Work_group;
		
		private string _Employee;
		
		private string _Description;
		
		private string _Information;
		
		private string _Service;
		
		private string _Ca_task_id;
		
		private string _Category;
		
		private string _Priority;
		
		private string _Status;
		
		private string _Sender;
		
		private System.DateTime _Cr_date;
		
		private System.DateTime _C_date;
		
		private System.DateTime _Complete_date;
		
		private System.DateTime _Date_of_start_work;
		
		private string _Decision;
		
		private string _Closing_code;
		
		private string _Deadline_breached;
		
		private string _Department_addressed;
		
		private string _Internal_division;
		
		private string _Addressed_structure;
		
		private string _Bank_addressed;
		
		private string _OP;
		
		private string _Type_of_services;
		
		private System.Nullable<int> _Counter_rediscovered;
		
		private string _Evaluation;
		
		private string _Id_service;
		
		private string _Id_CE;
		
		private string _Object;
		
		private string _Cause_of_incident;
		
		private string _Parent_group;
		
		private string _IntDiv_category;
		
		private string _Customer_comment;
		
		private System.Nullable<int> _Id_employee;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTo_the_target_dateChanging(string value);
    partial void OnTo_the_target_dateChanged();
    partial void OnId_sm_incChanging(string value);
    partial void OnId_sm_incChanged();
    partial void OnNumber_of_objectChanging(string value);
    partial void OnNumber_of_objectChanged();
    partial void OnWork_groupChanging(string value);
    partial void OnWork_groupChanged();
    partial void OnEmployeeChanging(string value);
    partial void OnEmployeeChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnInformationChanging(string value);
    partial void OnInformationChanged();
    partial void OnServiceChanging(string value);
    partial void OnServiceChanged();
    partial void OnCa_task_idChanging(string value);
    partial void OnCa_task_idChanged();
    partial void OnCategoryChanging(string value);
    partial void OnCategoryChanged();
    partial void OnPriorityChanging(string value);
    partial void OnPriorityChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnSenderChanging(string value);
    partial void OnSenderChanged();
    partial void OnCr_dateChanging(System.DateTime value);
    partial void OnCr_dateChanged();
    partial void OnC_dateChanging(System.DateTime value);
    partial void OnC_dateChanged();
    partial void OnComplete_dateChanging(System.DateTime value);
    partial void OnComplete_dateChanged();
    partial void OnDate_of_start_workChanging(System.DateTime value);
    partial void OnDate_of_start_workChanged();
    partial void OnDecisionChanging(string value);
    partial void OnDecisionChanged();
    partial void OnClosing_codeChanging(string value);
    partial void OnClosing_codeChanged();
    partial void OnDeadline_breachedChanging(string value);
    partial void OnDeadline_breachedChanged();
    partial void OnDepartment_addressedChanging(string value);
    partial void OnDepartment_addressedChanged();
    partial void OnInternal_divisionChanging(string value);
    partial void OnInternal_divisionChanged();
    partial void OnAddressed_structureChanging(string value);
    partial void OnAddressed_structureChanged();
    partial void OnBank_addressedChanging(string value);
    partial void OnBank_addressedChanged();
    partial void OnOPChanging(string value);
    partial void OnOPChanged();
    partial void OnType_of_servicesChanging(string value);
    partial void OnType_of_servicesChanged();
    partial void OnCounter_rediscoveredChanging(System.Nullable<int> value);
    partial void OnCounter_rediscoveredChanged();
    partial void OnEvaluationChanging(string value);
    partial void OnEvaluationChanged();
    partial void OnId_serviceChanging(string value);
    partial void OnId_serviceChanged();
    partial void OnId_CEChanging(string value);
    partial void OnId_CEChanged();
    partial void OnObjectChanging(string value);
    partial void OnObjectChanged();
    partial void OnCause_of_incidentChanging(string value);
    partial void OnCause_of_incidentChanged();
    partial void OnParent_groupChanging(string value);
    partial void OnParent_groupChanged();
    partial void OnIntDiv_categoryChanging(string value);
    partial void OnIntDiv_categoryChanged();
    partial void OnCustomer_commentChanging(string value);
    partial void OnCustomer_commentChanged();
    partial void OnId_employeeChanging(System.Nullable<int> value);
    partial void OnId_employeeChanged();
    #endregion
		
		public Sm_inc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="to_the_target_date", Storage="_To_the_target_date", DbType="NVarChar(250)")]
		public string To_the_target_date
		{
			get
			{
				return this._To_the_target_date;
			}
			set
			{
				if ((this._To_the_target_date != value))
				{
					this.OnTo_the_target_dateChanging(value);
					this.SendPropertyChanging();
					this._To_the_target_date = value;
					this.SendPropertyChanged("To_the_target_date");
					this.OnTo_the_target_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_sm_inc", Storage="_Id_sm_inc", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Id_sm_inc
		{
			get
			{
				return this._Id_sm_inc;
			}
			set
			{
				if ((this._Id_sm_inc != value))
				{
					this.OnId_sm_incChanging(value);
					this.SendPropertyChanging();
					this._Id_sm_inc = value;
					this.SendPropertyChanged("Id_sm_inc");
					this.OnId_sm_incChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="number_of_object", Storage="_Number_of_object", DbType="NVarChar(250)")]
		public string Number_of_object
		{
			get
			{
				return this._Number_of_object;
			}
			set
			{
				if ((this._Number_of_object != value))
				{
					this.OnNumber_of_objectChanging(value);
					this.SendPropertyChanging();
					this._Number_of_object = value;
					this.SendPropertyChanged("Number_of_object");
					this.OnNumber_of_objectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="work_group", Storage="_Work_group", DbType="NVarChar(250)")]
		public string Work_group
		{
			get
			{
				return this._Work_group;
			}
			set
			{
				if ((this._Work_group != value))
				{
					this.OnWork_groupChanging(value);
					this.SendPropertyChanging();
					this._Work_group = value;
					this.SendPropertyChanged("Work_group");
					this.OnWork_groupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="employee", Storage="_Employee", DbType="NVarChar(250)")]
		public string Employee
		{
			get
			{
				return this._Employee;
			}
			set
			{
				if ((this._Employee != value))
				{
					this.OnEmployeeChanging(value);
					this.SendPropertyChanging();
					this._Employee = value;
					this.SendPropertyChanged("Employee");
					this.OnEmployeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="description", Storage="_Description", DbType="NVarChar(250)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="information", Storage="_Information", DbType="NVarChar(250)")]
		public string Information
		{
			get
			{
				return this._Information;
			}
			set
			{
				if ((this._Information != value))
				{
					this.OnInformationChanging(value);
					this.SendPropertyChanging();
					this._Information = value;
					this.SendPropertyChanged("Information");
					this.OnInformationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="service", Storage="_Service", DbType="NVarChar(250)")]
		public string Service
		{
			get
			{
				return this._Service;
			}
			set
			{
				if ((this._Service != value))
				{
					this.OnServiceChanging(value);
					this.SendPropertyChanging();
					this._Service = value;
					this.SendPropertyChanged("Service");
					this.OnServiceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ca_task_id", Storage="_Ca_task_id", DbType="NVarChar(250)")]
		public string Ca_task_id
		{
			get
			{
				return this._Ca_task_id;
			}
			set
			{
				if ((this._Ca_task_id != value))
				{
					this.OnCa_task_idChanging(value);
					this.SendPropertyChanging();
					this._Ca_task_id = value;
					this.SendPropertyChanged("Ca_task_id");
					this.OnCa_task_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="category", Storage="_Category", DbType="NVarChar(250)")]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this.OnCategoryChanging(value);
					this.SendPropertyChanging();
					this._Category = value;
					this.SendPropertyChanged("Category");
					this.OnCategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="priority", Storage="_Priority", DbType="NVarChar(250)")]
		public string Priority
		{
			get
			{
				return this._Priority;
			}
			set
			{
				if ((this._Priority != value))
				{
					this.OnPriorityChanging(value);
					this.SendPropertyChanging();
					this._Priority = value;
					this.SendPropertyChanged("Priority");
					this.OnPriorityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="status", Storage="_Status", DbType="NVarChar(250)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="sender", Storage="_Sender", DbType="NVarChar(250)")]
		public string Sender
		{
			get
			{
				return this._Sender;
			}
			set
			{
				if ((this._Sender != value))
				{
					this.OnSenderChanging(value);
					this.SendPropertyChanging();
					this._Sender = value;
					this.SendPropertyChanged("Sender");
					this.OnSenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="cr_date", Storage="_Cr_date", DbType="DateTime NOT NULL")]
		public System.DateTime Cr_date
		{
			get
			{
				return this._Cr_date;
			}
			set
			{
				if ((this._Cr_date != value))
				{
					this.OnCr_dateChanging(value);
					this.SendPropertyChanging();
					this._Cr_date = value;
					this.SendPropertyChanged("Cr_date");
					this.OnCr_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="c_date", Storage="_C_date", DbType="DateTime NOT NULL")]
		public System.DateTime C_date
		{
			get
			{
				return this._C_date;
			}
			set
			{
				if ((this._C_date != value))
				{
					this.OnC_dateChanging(value);
					this.SendPropertyChanging();
					this._C_date = value;
					this.SendPropertyChanged("C_date");
					this.OnC_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="complete_date", Storage="_Complete_date", DbType="DateTime NOT NULL")]
		public System.DateTime Complete_date
		{
			get
			{
				return this._Complete_date;
			}
			set
			{
				if ((this._Complete_date != value))
				{
					this.OnComplete_dateChanging(value);
					this.SendPropertyChanging();
					this._Complete_date = value;
					this.SendPropertyChanged("Complete_date");
					this.OnComplete_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="date_of_start_work", Storage="_Date_of_start_work", DbType="DateTime NOT NULL")]
		public System.DateTime Date_of_start_work
		{
			get
			{
				return this._Date_of_start_work;
			}
			set
			{
				if ((this._Date_of_start_work != value))
				{
					this.OnDate_of_start_workChanging(value);
					this.SendPropertyChanging();
					this._Date_of_start_work = value;
					this.SendPropertyChanged("Date_of_start_work");
					this.OnDate_of_start_workChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="decision", Storage="_Decision", DbType="NVarChar(250)")]
		public string Decision
		{
			get
			{
				return this._Decision;
			}
			set
			{
				if ((this._Decision != value))
				{
					this.OnDecisionChanging(value);
					this.SendPropertyChanging();
					this._Decision = value;
					this.SendPropertyChanged("Decision");
					this.OnDecisionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="closing_code", Storage="_Closing_code", DbType="NVarChar(250)")]
		public string Closing_code
		{
			get
			{
				return this._Closing_code;
			}
			set
			{
				if ((this._Closing_code != value))
				{
					this.OnClosing_codeChanging(value);
					this.SendPropertyChanging();
					this._Closing_code = value;
					this.SendPropertyChanged("Closing_code");
					this.OnClosing_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="deadline_breached", Storage="_Deadline_breached", DbType="NVarChar(250)")]
		public string Deadline_breached
		{
			get
			{
				return this._Deadline_breached;
			}
			set
			{
				if ((this._Deadline_breached != value))
				{
					this.OnDeadline_breachedChanging(value);
					this.SendPropertyChanging();
					this._Deadline_breached = value;
					this.SendPropertyChanged("Deadline_breached");
					this.OnDeadline_breachedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="department_addressed", Storage="_Department_addressed", DbType="NVarChar(250)")]
		public string Department_addressed
		{
			get
			{
				return this._Department_addressed;
			}
			set
			{
				if ((this._Department_addressed != value))
				{
					this.OnDepartment_addressedChanging(value);
					this.SendPropertyChanging();
					this._Department_addressed = value;
					this.SendPropertyChanged("Department_addressed");
					this.OnDepartment_addressedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="internal_division", Storage="_Internal_division", DbType="NVarChar(250)")]
		public string Internal_division
		{
			get
			{
				return this._Internal_division;
			}
			set
			{
				if ((this._Internal_division != value))
				{
					this.OnInternal_divisionChanging(value);
					this.SendPropertyChanging();
					this._Internal_division = value;
					this.SendPropertyChanged("Internal_division");
					this.OnInternal_divisionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="addressed_structure", Storage="_Addressed_structure", DbType="NVarChar(250)")]
		public string Addressed_structure
		{
			get
			{
				return this._Addressed_structure;
			}
			set
			{
				if ((this._Addressed_structure != value))
				{
					this.OnAddressed_structureChanging(value);
					this.SendPropertyChanging();
					this._Addressed_structure = value;
					this.SendPropertyChanged("Addressed_structure");
					this.OnAddressed_structureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="bank_addressed", Storage="_Bank_addressed", DbType="NVarChar(250)")]
		public string Bank_addressed
		{
			get
			{
				return this._Bank_addressed;
			}
			set
			{
				if ((this._Bank_addressed != value))
				{
					this.OnBank_addressedChanging(value);
					this.SendPropertyChanging();
					this._Bank_addressed = value;
					this.SendPropertyChanged("Bank_addressed");
					this.OnBank_addressedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OP", DbType="NVarChar(250)")]
		public string OP
		{
			get
			{
				return this._OP;
			}
			set
			{
				if ((this._OP != value))
				{
					this.OnOPChanging(value);
					this.SendPropertyChanging();
					this._OP = value;
					this.SendPropertyChanged("OP");
					this.OnOPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="type_of_services", Storage="_Type_of_services", DbType="NVarChar(250)")]
		public string Type_of_services
		{
			get
			{
				return this._Type_of_services;
			}
			set
			{
				if ((this._Type_of_services != value))
				{
					this.OnType_of_servicesChanging(value);
					this.SendPropertyChanging();
					this._Type_of_services = value;
					this.SendPropertyChanged("Type_of_services");
					this.OnType_of_servicesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="counter_rediscovered", Storage="_Counter_rediscovered", DbType="Int")]
		public System.Nullable<int> Counter_rediscovered
		{
			get
			{
				return this._Counter_rediscovered;
			}
			set
			{
				if ((this._Counter_rediscovered != value))
				{
					this.OnCounter_rediscoveredChanging(value);
					this.SendPropertyChanging();
					this._Counter_rediscovered = value;
					this.SendPropertyChanged("Counter_rediscovered");
					this.OnCounter_rediscoveredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="evaluation", Storage="_Evaluation", DbType="NVarChar(250)")]
		public string Evaluation
		{
			get
			{
				return this._Evaluation;
			}
			set
			{
				if ((this._Evaluation != value))
				{
					this.OnEvaluationChanging(value);
					this.SendPropertyChanging();
					this._Evaluation = value;
					this.SendPropertyChanged("Evaluation");
					this.OnEvaluationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_service", Storage="_Id_service", DbType="NVarChar(250)")]
		public string Id_service
		{
			get
			{
				return this._Id_service;
			}
			set
			{
				if ((this._Id_service != value))
				{
					this.OnId_serviceChanging(value);
					this.SendPropertyChanging();
					this._Id_service = value;
					this.SendPropertyChanged("Id_service");
					this.OnId_serviceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_CE", Storage="_Id_CE", DbType="NVarChar(250)")]
		public string Id_CE
		{
			get
			{
				return this._Id_CE;
			}
			set
			{
				if ((this._Id_CE != value))
				{
					this.OnId_CEChanging(value);
					this.SendPropertyChanging();
					this._Id_CE = value;
					this.SendPropertyChanged("Id_CE");
					this.OnId_CEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="object", Storage="_Object", DbType="NVarChar(250)")]
		public string Object
		{
			get
			{
				return this._Object;
			}
			set
			{
				if ((this._Object != value))
				{
					this.OnObjectChanging(value);
					this.SendPropertyChanging();
					this._Object = value;
					this.SendPropertyChanged("Object");
					this.OnObjectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="cause_of_incident", Storage="_Cause_of_incident", DbType="NVarChar(250)")]
		public string Cause_of_incident
		{
			get
			{
				return this._Cause_of_incident;
			}
			set
			{
				if ((this._Cause_of_incident != value))
				{
					this.OnCause_of_incidentChanging(value);
					this.SendPropertyChanging();
					this._Cause_of_incident = value;
					this.SendPropertyChanged("Cause_of_incident");
					this.OnCause_of_incidentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="parent_group", Storage="_Parent_group", DbType="NVarChar(250)")]
		public string Parent_group
		{
			get
			{
				return this._Parent_group;
			}
			set
			{
				if ((this._Parent_group != value))
				{
					this.OnParent_groupChanging(value);
					this.SendPropertyChanging();
					this._Parent_group = value;
					this.SendPropertyChanged("Parent_group");
					this.OnParent_groupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IntDiv_category", DbType="NVarChar(250)")]
		public string IntDiv_category
		{
			get
			{
				return this._IntDiv_category;
			}
			set
			{
				if ((this._IntDiv_category != value))
				{
					this.OnIntDiv_categoryChanging(value);
					this.SendPropertyChanging();
					this._IntDiv_category = value;
					this.SendPropertyChanged("IntDiv_category");
					this.OnIntDiv_categoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="customer_comment", Storage="_Customer_comment", DbType="NVarChar(250)")]
		public string Customer_comment
		{
			get
			{
				return this._Customer_comment;
			}
			set
			{
				if ((this._Customer_comment != value))
				{
					this.OnCustomer_commentChanging(value);
					this.SendPropertyChanging();
					this._Customer_comment = value;
					this.SendPropertyChanged("Customer_comment");
					this.OnCustomer_commentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_employee", Storage="_Id_employee", DbType="Int")]
		public System.Nullable<int> Id_employee
		{
			get
			{
				return this._Id_employee;
			}
			set
			{
				if ((this._Id_employee != value))
				{
					this.OnId_employeeChanging(value);
					this.SendPropertyChanging();
					this._Id_employee = value;
					this.SendPropertyChanged("Id_employee");
					this.OnId_employeeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="sm_zno")]
	public partial class Sm_zno : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _To_the_target_date;
		
		private string _Id_sm_zno;
		
		private string _Number_of_object;
		
		private string _Work_group;
		
		private string _Employee;
		
		private string _Description;
		
		private string _Information;
		
		private string _Service;
		
		private string _Ca_task_id;
		
		private string _Category;
		
		private string _Priority;
		
		private string _Status;
		
		private string _Sender;
		
		private System.DateTime _Cr_date;
		
		private System.DateTime _C_date;
		
		private System.DateTime _Complete_date;
		
		private System.DateTime _Date_of_start_work;
		
		private string _Decision;
		
		private string _Closing_code;
		
		private string _Deadline_breached;
		
		private string _Department_addressed;
		
		private string _Internal_division;
		
		private string _Addressed_structure;
		
		private string _Bank_addressed;
		
		private string _OP;
		
		private string _Type_of_services;
		
		private System.Nullable<int> _Counter_rediscovered;
		
		private string _Evaluation;
		
		private string _Id_service;
		
		private string _Id_CE;
		
		private string _Object;
		
		private string _Cause_of_incident;
		
		private string _Parent_group;
		
		private string _IntDiv_category;
		
		private string _Customer_comment;
		
		private System.Nullable<int> _Id_employee;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTo_the_target_dateChanging(string value);
    partial void OnTo_the_target_dateChanged();
    partial void OnId_sm_znoChanging(string value);
    partial void OnId_sm_znoChanged();
    partial void OnNumber_of_objectChanging(string value);
    partial void OnNumber_of_objectChanged();
    partial void OnWork_groupChanging(string value);
    partial void OnWork_groupChanged();
    partial void OnEmployeeChanging(string value);
    partial void OnEmployeeChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnInformationChanging(string value);
    partial void OnInformationChanged();
    partial void OnServiceChanging(string value);
    partial void OnServiceChanged();
    partial void OnCa_task_idChanging(string value);
    partial void OnCa_task_idChanged();
    partial void OnCategoryChanging(string value);
    partial void OnCategoryChanged();
    partial void OnPriorityChanging(string value);
    partial void OnPriorityChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnSenderChanging(string value);
    partial void OnSenderChanged();
    partial void OnCr_dateChanging(System.DateTime value);
    partial void OnCr_dateChanged();
    partial void OnC_dateChanging(System.DateTime value);
    partial void OnC_dateChanged();
    partial void OnComplete_dateChanging(System.DateTime value);
    partial void OnComplete_dateChanged();
    partial void OnDate_of_start_workChanging(System.DateTime value);
    partial void OnDate_of_start_workChanged();
    partial void OnDecisionChanging(string value);
    partial void OnDecisionChanged();
    partial void OnClosing_codeChanging(string value);
    partial void OnClosing_codeChanged();
    partial void OnDeadline_breachedChanging(string value);
    partial void OnDeadline_breachedChanged();
    partial void OnDepartment_addressedChanging(string value);
    partial void OnDepartment_addressedChanged();
    partial void OnInternal_divisionChanging(string value);
    partial void OnInternal_divisionChanged();
    partial void OnAddressed_structureChanging(string value);
    partial void OnAddressed_structureChanged();
    partial void OnBank_addressedChanging(string value);
    partial void OnBank_addressedChanged();
    partial void OnOPChanging(string value);
    partial void OnOPChanged();
    partial void OnType_of_servicesChanging(string value);
    partial void OnType_of_servicesChanged();
    partial void OnCounter_rediscoveredChanging(System.Nullable<int> value);
    partial void OnCounter_rediscoveredChanged();
    partial void OnEvaluationChanging(string value);
    partial void OnEvaluationChanged();
    partial void OnId_serviceChanging(string value);
    partial void OnId_serviceChanged();
    partial void OnId_CEChanging(string value);
    partial void OnId_CEChanged();
    partial void OnObjectChanging(string value);
    partial void OnObjectChanged();
    partial void OnCause_of_incidentChanging(string value);
    partial void OnCause_of_incidentChanged();
    partial void OnParent_groupChanging(string value);
    partial void OnParent_groupChanged();
    partial void OnIntDiv_categoryChanging(string value);
    partial void OnIntDiv_categoryChanged();
    partial void OnCustomer_commentChanging(string value);
    partial void OnCustomer_commentChanged();
    partial void OnId_employeeChanging(System.Nullable<int> value);
    partial void OnId_employeeChanged();
    #endregion
		
		public Sm_zno()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="to_the_target_date", Storage="_To_the_target_date", DbType="NVarChar(250)")]
		public string To_the_target_date
		{
			get
			{
				return this._To_the_target_date;
			}
			set
			{
				if ((this._To_the_target_date != value))
				{
					this.OnTo_the_target_dateChanging(value);
					this.SendPropertyChanging();
					this._To_the_target_date = value;
					this.SendPropertyChanged("To_the_target_date");
					this.OnTo_the_target_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_sm_zno", Storage="_Id_sm_zno", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Id_sm_zno
		{
			get
			{
				return this._Id_sm_zno;
			}
			set
			{
				if ((this._Id_sm_zno != value))
				{
					this.OnId_sm_znoChanging(value);
					this.SendPropertyChanging();
					this._Id_sm_zno = value;
					this.SendPropertyChanged("Id_sm_zno");
					this.OnId_sm_znoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="number_of_object", Storage="_Number_of_object", DbType="NVarChar(250)")]
		public string Number_of_object
		{
			get
			{
				return this._Number_of_object;
			}
			set
			{
				if ((this._Number_of_object != value))
				{
					this.OnNumber_of_objectChanging(value);
					this.SendPropertyChanging();
					this._Number_of_object = value;
					this.SendPropertyChanged("Number_of_object");
					this.OnNumber_of_objectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="work_group", Storage="_Work_group", DbType="NVarChar(250)")]
		public string Work_group
		{
			get
			{
				return this._Work_group;
			}
			set
			{
				if ((this._Work_group != value))
				{
					this.OnWork_groupChanging(value);
					this.SendPropertyChanging();
					this._Work_group = value;
					this.SendPropertyChanged("Work_group");
					this.OnWork_groupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="employee", Storage="_Employee", DbType="NVarChar(250)")]
		public string Employee
		{
			get
			{
				return this._Employee;
			}
			set
			{
				if ((this._Employee != value))
				{
					this.OnEmployeeChanging(value);
					this.SendPropertyChanging();
					this._Employee = value;
					this.SendPropertyChanged("Employee");
					this.OnEmployeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="description", Storage="_Description", DbType="NVarChar(250)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="information", Storage="_Information", DbType="NVarChar(250)")]
		public string Information
		{
			get
			{
				return this._Information;
			}
			set
			{
				if ((this._Information != value))
				{
					this.OnInformationChanging(value);
					this.SendPropertyChanging();
					this._Information = value;
					this.SendPropertyChanged("Information");
					this.OnInformationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="service", Storage="_Service", DbType="NVarChar(250)")]
		public string Service
		{
			get
			{
				return this._Service;
			}
			set
			{
				if ((this._Service != value))
				{
					this.OnServiceChanging(value);
					this.SendPropertyChanging();
					this._Service = value;
					this.SendPropertyChanged("Service");
					this.OnServiceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ca_task_id", Storage="_Ca_task_id", DbType="NVarChar(250)")]
		public string Ca_task_id
		{
			get
			{
				return this._Ca_task_id;
			}
			set
			{
				if ((this._Ca_task_id != value))
				{
					this.OnCa_task_idChanging(value);
					this.SendPropertyChanging();
					this._Ca_task_id = value;
					this.SendPropertyChanged("Ca_task_id");
					this.OnCa_task_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="category", Storage="_Category", DbType="NVarChar(250)")]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this.OnCategoryChanging(value);
					this.SendPropertyChanging();
					this._Category = value;
					this.SendPropertyChanged("Category");
					this.OnCategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="priority", Storage="_Priority", DbType="NVarChar(250)")]
		public string Priority
		{
			get
			{
				return this._Priority;
			}
			set
			{
				if ((this._Priority != value))
				{
					this.OnPriorityChanging(value);
					this.SendPropertyChanging();
					this._Priority = value;
					this.SendPropertyChanged("Priority");
					this.OnPriorityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="status", Storage="_Status", DbType="NVarChar(250)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="sender", Storage="_Sender", DbType="NVarChar(250)")]
		public string Sender
		{
			get
			{
				return this._Sender;
			}
			set
			{
				if ((this._Sender != value))
				{
					this.OnSenderChanging(value);
					this.SendPropertyChanging();
					this._Sender = value;
					this.SendPropertyChanged("Sender");
					this.OnSenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="cr_date", Storage="_Cr_date", DbType="DateTime NOT NULL")]
		public System.DateTime Cr_date
		{
			get
			{
				return this._Cr_date;
			}
			set
			{
				if ((this._Cr_date != value))
				{
					this.OnCr_dateChanging(value);
					this.SendPropertyChanging();
					this._Cr_date = value;
					this.SendPropertyChanged("Cr_date");
					this.OnCr_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="c_date", Storage="_C_date", DbType="DateTime NOT NULL")]
		public System.DateTime C_date
		{
			get
			{
				return this._C_date;
			}
			set
			{
				if ((this._C_date != value))
				{
					this.OnC_dateChanging(value);
					this.SendPropertyChanging();
					this._C_date = value;
					this.SendPropertyChanged("C_date");
					this.OnC_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="complete_date", Storage="_Complete_date", DbType="DateTime NOT NULL")]
		public System.DateTime Complete_date
		{
			get
			{
				return this._Complete_date;
			}
			set
			{
				if ((this._Complete_date != value))
				{
					this.OnComplete_dateChanging(value);
					this.SendPropertyChanging();
					this._Complete_date = value;
					this.SendPropertyChanged("Complete_date");
					this.OnComplete_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="date_of_start_work", Storage="_Date_of_start_work", DbType="DateTime NOT NULL")]
		public System.DateTime Date_of_start_work
		{
			get
			{
				return this._Date_of_start_work;
			}
			set
			{
				if ((this._Date_of_start_work != value))
				{
					this.OnDate_of_start_workChanging(value);
					this.SendPropertyChanging();
					this._Date_of_start_work = value;
					this.SendPropertyChanged("Date_of_start_work");
					this.OnDate_of_start_workChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="decision", Storage="_Decision", DbType="NVarChar(250)")]
		public string Decision
		{
			get
			{
				return this._Decision;
			}
			set
			{
				if ((this._Decision != value))
				{
					this.OnDecisionChanging(value);
					this.SendPropertyChanging();
					this._Decision = value;
					this.SendPropertyChanged("Decision");
					this.OnDecisionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="closing_code", Storage="_Closing_code", DbType="NVarChar(250)")]
		public string Closing_code
		{
			get
			{
				return this._Closing_code;
			}
			set
			{
				if ((this._Closing_code != value))
				{
					this.OnClosing_codeChanging(value);
					this.SendPropertyChanging();
					this._Closing_code = value;
					this.SendPropertyChanged("Closing_code");
					this.OnClosing_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="deadline_breached", Storage="_Deadline_breached", DbType="NVarChar(250)")]
		public string Deadline_breached
		{
			get
			{
				return this._Deadline_breached;
			}
			set
			{
				if ((this._Deadline_breached != value))
				{
					this.OnDeadline_breachedChanging(value);
					this.SendPropertyChanging();
					this._Deadline_breached = value;
					this.SendPropertyChanged("Deadline_breached");
					this.OnDeadline_breachedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="department_addressed", Storage="_Department_addressed", DbType="NVarChar(250)")]
		public string Department_addressed
		{
			get
			{
				return this._Department_addressed;
			}
			set
			{
				if ((this._Department_addressed != value))
				{
					this.OnDepartment_addressedChanging(value);
					this.SendPropertyChanging();
					this._Department_addressed = value;
					this.SendPropertyChanged("Department_addressed");
					this.OnDepartment_addressedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="internal_division", Storage="_Internal_division", DbType="NVarChar(250)")]
		public string Internal_division
		{
			get
			{
				return this._Internal_division;
			}
			set
			{
				if ((this._Internal_division != value))
				{
					this.OnInternal_divisionChanging(value);
					this.SendPropertyChanging();
					this._Internal_division = value;
					this.SendPropertyChanged("Internal_division");
					this.OnInternal_divisionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="addressed_structure", Storage="_Addressed_structure", DbType="NVarChar(250)")]
		public string Addressed_structure
		{
			get
			{
				return this._Addressed_structure;
			}
			set
			{
				if ((this._Addressed_structure != value))
				{
					this.OnAddressed_structureChanging(value);
					this.SendPropertyChanging();
					this._Addressed_structure = value;
					this.SendPropertyChanged("Addressed_structure");
					this.OnAddressed_structureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="bank_addressed", Storage="_Bank_addressed", DbType="NVarChar(250)")]
		public string Bank_addressed
		{
			get
			{
				return this._Bank_addressed;
			}
			set
			{
				if ((this._Bank_addressed != value))
				{
					this.OnBank_addressedChanging(value);
					this.SendPropertyChanging();
					this._Bank_addressed = value;
					this.SendPropertyChanged("Bank_addressed");
					this.OnBank_addressedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OP", DbType="NVarChar(250)")]
		public string OP
		{
			get
			{
				return this._OP;
			}
			set
			{
				if ((this._OP != value))
				{
					this.OnOPChanging(value);
					this.SendPropertyChanging();
					this._OP = value;
					this.SendPropertyChanged("OP");
					this.OnOPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="type_of_services", Storage="_Type_of_services", DbType="NVarChar(250)")]
		public string Type_of_services
		{
			get
			{
				return this._Type_of_services;
			}
			set
			{
				if ((this._Type_of_services != value))
				{
					this.OnType_of_servicesChanging(value);
					this.SendPropertyChanging();
					this._Type_of_services = value;
					this.SendPropertyChanged("Type_of_services");
					this.OnType_of_servicesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="counter_rediscovered", Storage="_Counter_rediscovered", DbType="Int")]
		public System.Nullable<int> Counter_rediscovered
		{
			get
			{
				return this._Counter_rediscovered;
			}
			set
			{
				if ((this._Counter_rediscovered != value))
				{
					this.OnCounter_rediscoveredChanging(value);
					this.SendPropertyChanging();
					this._Counter_rediscovered = value;
					this.SendPropertyChanged("Counter_rediscovered");
					this.OnCounter_rediscoveredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="evaluation", Storage="_Evaluation", DbType="NVarChar(250)")]
		public string Evaluation
		{
			get
			{
				return this._Evaluation;
			}
			set
			{
				if ((this._Evaluation != value))
				{
					this.OnEvaluationChanging(value);
					this.SendPropertyChanging();
					this._Evaluation = value;
					this.SendPropertyChanged("Evaluation");
					this.OnEvaluationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_service", Storage="_Id_service", DbType="NVarChar(250)")]
		public string Id_service
		{
			get
			{
				return this._Id_service;
			}
			set
			{
				if ((this._Id_service != value))
				{
					this.OnId_serviceChanging(value);
					this.SendPropertyChanging();
					this._Id_service = value;
					this.SendPropertyChanged("Id_service");
					this.OnId_serviceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_CE", Storage="_Id_CE", DbType="NVarChar(250)")]
		public string Id_CE
		{
			get
			{
				return this._Id_CE;
			}
			set
			{
				if ((this._Id_CE != value))
				{
					this.OnId_CEChanging(value);
					this.SendPropertyChanging();
					this._Id_CE = value;
					this.SendPropertyChanged("Id_CE");
					this.OnId_CEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="object", Storage="_Object", DbType="NVarChar(250)")]
		public string Object
		{
			get
			{
				return this._Object;
			}
			set
			{
				if ((this._Object != value))
				{
					this.OnObjectChanging(value);
					this.SendPropertyChanging();
					this._Object = value;
					this.SendPropertyChanged("Object");
					this.OnObjectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="cause_of_incident", Storage="_Cause_of_incident", DbType="NVarChar(250)")]
		public string Cause_of_incident
		{
			get
			{
				return this._Cause_of_incident;
			}
			set
			{
				if ((this._Cause_of_incident != value))
				{
					this.OnCause_of_incidentChanging(value);
					this.SendPropertyChanging();
					this._Cause_of_incident = value;
					this.SendPropertyChanged("Cause_of_incident");
					this.OnCause_of_incidentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="parent_group", Storage="_Parent_group", DbType="NVarChar(250)")]
		public string Parent_group
		{
			get
			{
				return this._Parent_group;
			}
			set
			{
				if ((this._Parent_group != value))
				{
					this.OnParent_groupChanging(value);
					this.SendPropertyChanging();
					this._Parent_group = value;
					this.SendPropertyChanged("Parent_group");
					this.OnParent_groupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IntDiv_category", DbType="NVarChar(250)")]
		public string IntDiv_category
		{
			get
			{
				return this._IntDiv_category;
			}
			set
			{
				if ((this._IntDiv_category != value))
				{
					this.OnIntDiv_categoryChanging(value);
					this.SendPropertyChanging();
					this._IntDiv_category = value;
					this.SendPropertyChanged("IntDiv_category");
					this.OnIntDiv_categoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="customer_comment", Storage="_Customer_comment", DbType="NVarChar(250)")]
		public string Customer_comment
		{
			get
			{
				return this._Customer_comment;
			}
			set
			{
				if ((this._Customer_comment != value))
				{
					this.OnCustomer_commentChanging(value);
					this.SendPropertyChanging();
					this._Customer_comment = value;
					this.SendPropertyChanged("Customer_comment");
					this.OnCustomer_commentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_employee", Storage="_Id_employee", DbType="Int")]
		public System.Nullable<int> Id_employee
		{
			get
			{
				return this._Id_employee;
			}
			set
			{
				if ((this._Id_employee != value))
				{
					this.OnId_employeeChanging(value);
					this.SendPropertyChanging();
					this._Id_employee = value;
					this.SendPropertyChanged("Id_employee");
					this.OnId_employeeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
